import type { Metadata } from "next";
import type { CSSProperties, ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const fontVariables = {
    "--font-geist-sans": '"Segoe UI", "Helvetica Neue", Arial, system-ui, sans-serif',
    "--font-geist-mono": '"SF Mono", "Cascadia Code", "Menlo", "Consolas", monospace',
    "--font-jetbrains-mono": '"Cascadia Code", "SF Mono", "Menlo", "Consolas", monospace',
  } as CSSProperties;

  return (
    <html lang="en">
      <body className="antialiased" style={fontVariables}>
        {children}
      </body>
    </html>
  );
}
